version: 2

# Define the build environment and tools
build:
  os: ubuntu-22.04  # Ensure a recent Ubuntu version is used
  tools:
    python: "3.10"  # Set the Python version to use
  apt_packages:  
    - build-essential  # Provides GCC and other build tools
    - cmake            # CMake to configure and build the project
    - python3-dev      # Required for compiling Python extensions

  jobs:
    post_install:

      # Step 1: Install Poetry
      - pip install poetry

      # Step 2: Configure Poetry to use the ReadTheDocs virtual environment
      - poetry config virtualenvs.create false

      # Step 3: Create a build directory and configure the C++ project with CMake
      - mkdir -p build
      - cmake -B build -S .  # Configure CMake, specifying build dir (-B) and source dir (-S)

      # Step 4: Build the C++ project
      - cmake --build build  # Build the project in the "build" directory

      # Step 5: Copy the built shared library (bindings) to the expected location
      - cp build/screamer_bindings*.so screamer/

      # Step 6: Install the documentation dependencies with Poetry in the existing virtual environment
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m poetry install --only docs

# Build documentation in the docs directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py  # Path to the Sphinx configuration file
