[tool.poetry]
name = "screamer"
version = "0.1.0"
description = "Screamingly fast streaming indicators with C++ performance and Python simplicity."

authors = ["Thijs van den Berg <thijs@sitmo.com>, Mohammadjavad Vakili <Mohammadjavad.Vakili@shell.com>"]

maintainers = [
    "Thijs van den Berg <thijs@sitmo.com>", 
    "Mohammadjavad Vakili <Mohammadjavad.Vakili@shell.com>" 
]


license = "MIT"
readme = "README.md"
packages = [{ include = "screamer" }]

[tool.poetry.dependencies]
python = "^3.9"
pybind11 = "^2.9"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["setuptools", "wheel", "pybind11", "scikit-build"]
build-backend = "setuptools.build_meta"