# DO NOT MODIFY, THIS FILE IS AUTOGENERATED
# screamer/__init__.py

__version__ = "Unreleased"

from .screamer_bindings import (
    Diff,
    Lag,
    LogReturn,
    Return,
    RollingSum,
    SMA             
)

from .generators import (
    diff_generator,
    lag_generator,
    log_return_generator,
    return_generator,
    rolling_sum_generator,
    sma_generator             
)

__all__ = [
    "Diff", "diff_generator",
    "Lag", "lag_generator",
    "LogReturn", "log_return_generator",
    "Return", "return_generator",
    "RollingSum", "rolling_sum_generator",
    "SMA", "sma_generator"
]
