name: CI

on:
  push:
    branches: [ mainx ]
  pull_request:
    branches: [ mainx ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest]
        python-version: [ '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-build cmake ninja pybind11 pytest

    - name: Build and install the package
      run: |
        pip install . -v

    - name: Run C++ Tests
      run: |
        ctest --output-on-failure

    - name: Run Python Tests
      run: |
        pytest
