name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-build cmake ninja pybind11 pytest

    - name: Build and install the package
      run: |
        pip install . -v

    - name: List screamer installation
      run: |
        find $(python -c 'import site; print(site.getsitepackages()[0])')/screamer

    - name: List build directory
      run: |
        ls -la
        ls -R build

    - name: Run C++ Tests
      run: |
        ctest --output-on-failure

    - name: Run Python Tests
      run: |
        pytest
