name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v3
      with:
        cmake-version: '3.21.1'

    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Run C++ Tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Run Python Tests
      run: |
        poetry run pytest
