name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install sphinx sphinx-autodoc-typehints breathe sphinx_rtd_theme

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --only docs
  
      - name: Build documentation
        run: |
          cd docs
          make html