name: Build and Publish

on:
  push:
    tags: 'v*'

permissions:
  contents: read
  id-token: write  # Required for PyPI Trusted Publishers

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install Python development headers for Ubuntu
    - name: Install Python development headers (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y python3-dev

    # Install equivalent packages for macOS and Windows if necessary
    - name: Install dependencies for macOS
      if: matrix.os == 'macos-latest'
      run: brew install python@3.9  # Adjust version as needed

    # For Windows, the setup-python action should already provide Python libraries.
    
    - name: Install cibuildwheel
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==2.14.1

    # Install build dependencies
    - name: Install build dependencies
      run: |
        python -m pip install scikit-build cmake ninja pybind11

    - name: Build wheels
      env:
        CIBW_BUILD_VERBOSITY: 1
        CIBW_BEFORE_BUILD: python -m pip install scikit-build cmake ninja pybind11
        CIBW_BUILD: cp39-* cp310-* cp311-*
        CIBW_TEST_COMMAND: ""
      run: |
        cibuildwheel --output-dir wheelhouse

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels-${{ matrix.os }}
        path: wheelhouse/*.whl

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Download wheels
      uses: actions/download-artifact@v3
      with:
        name: wheels-ubuntu-latest
    - uses: actions/download-artifact@v3
      with:
        name: wheels-macos-latest
    - uses: actions/download-artifact@v3
      with:
        name: wheels-windows-latest

    - name: Combine wheels
      run: |
        mkdir all_wheels
        find . -name '*.whl' -exec mv {} all_wheels/ \;
      
    - name: Publish to PyPI via Trusted Publishers
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ./all_wheels
