name: Build and Publish

on:
  push:
    tags: 'v*'

permissions:
  contents: read
  id-token: write  # Required for PyPI Trusted Publishers

jobs:
  build_and_publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install cibuildwheel
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==2.14.1

    # Install build dependencies
    - name: Install build dependencies
      run: |
        python -m pip install scikit-build cmake ninja pybind11

    - name: Build wheels
      env:
        CIBW_BUILD_VERBOSITY: 1
        CIBW_BEFORE_BUILD: python -m pip install scikit-build cmake ninja pybind11
        CIBW_BUILD: cp39-* cp310-* cp311-*
        CIBW_TEST_COMMAND: ""
      run: |
        cibuildwheel --output-dir wheelhouse

    - name: Publish to PyPI via Trusted Publishers
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages_dir: ./wheelhouse
      env:
        # The PyPI Publisher ID provided by PyPI after configuration
        PYPI_PUBLISHER_ID: ${{ secrets.PYPI_PUBLISHER_ID }}

