name: Build and Publish

on:
  push:
    tags: 'v*'

permissions:
  contents: read
  id-token: write  # Required for PyPI Trusted Publishers

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]


    steps:
    - uses: actions/checkout@v4   

    # Used to host cibuildwheel
    - uses: actions/setup-python@v5

    # Install cibuildwheel and build dependencies for all platforms
    - name: Install cibuildwheel and build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==2.21.3 scikit-build cmake ninja pybind11

    - name: Build wheels
      env:
        CIBW_BUILD_VERBOSITY: 1
        CIBW_BUILD: cp39-* cp310-* cp311-*
        CIBW_TEST_COMMAND: ""
      run: |
        cibuildwheel --output-dir wheelhouse

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels-${{ matrix.os }}
        path: wheelhouse/*.whl

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Download wheels
      uses: actions/download-artifact@v3
      with:
        name: wheels-ubuntu-latest
    - uses: actions/download-artifact@v3
      with:
        name: wheels-macos-latest
    - uses: actions/download-artifact@v3
      with:
        name: wheels-windows-latest

    - name: Combine wheels
      run: |
        mkdir all_wheels
        find . -name '*.whl' -exec mv {} all_wheels/ \;
      
    - name: Publish to PyPI via Trusted Publishers
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ./all_wheels
